SET FOREIGN_KEY_CHECK = 0;
DROP DATABASE IF EXISTS EMPRESA;
CREATE DATABASE EMPRESA;
USE EMPRESA;
CREATE TABLE emp (
    num INTEGER,
    nom VARCHAR(10) NOT NULL,
    cap INTEGER,
    comissio INTEGER,
    dept INTEGER NOT NULL
);
CREATE TABLE dept (
    codi INTEGER PRIMARY KEY,
    nom VARCHAR(15) NOT NULL UNIQUE,
    poble VARCHAR(20)
);

SET FOREIGN_KEY_CHECK = 1;

-- 3
ALTER TABLE emp ADD PRIMARY KEY(num);
-- 4
ALTER TABLE emp ADD COLUMN salari INT NOT NULL;
-- 5
ALTER TABLE emp ADD FOREIGN KEY (dept) REFERENCES dept(codi)
                ON DELETE CASCADE;
-- 6
ALTER TABLE emp ADD FOREIGN KEY (cap) REFERENCES emp(codi);
-- 7
ALTER TABLE emp DROP COLUMN cap;
-- 8
ALTER TABLE dept DROP PRIMARY KEY;